// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuyHm99R33uqy_VoF8gjh4q6Etl3azC9s',
    appId: '1:709846745958:web:fd23c8a7d73472d42a7ea7',
    messagingSenderId: '709846745958',
    projectId: 'chat-app-b5912',
    authDomain: 'chat-app-b5912.firebaseapp.com',
    storageBucket: 'chat-app-b5912.appspot.com',
    measurementId: 'G-273LBLT302',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY17cVfkholSNNAdnvN9668zyygOUA23E',
    appId: '1:709846745958:android:488d903a46ab3cd52a7ea7',
    messagingSenderId: '709846745958',
    projectId: 'chat-app-b5912',
    storageBucket: 'chat-app-b5912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD5uLn7zOmG76cpIyFHd6N12HuL28vKh8',
    appId: '1:709846745958:ios:2f4785cbc46282202a7ea7',
    messagingSenderId: '709846745958',
    projectId: 'chat-app-b5912',
    storageBucket: 'chat-app-b5912.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD5uLn7zOmG76cpIyFHd6N12HuL28vKh8',
    appId: '1:709846745958:ios:9d782a453ca147c82a7ea7',
    messagingSenderId: '709846745958',
    projectId: 'chat-app-b5912',
    storageBucket: 'chat-app-b5912.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
